language: R
cache: packages
r_binary_packages:
 - testthat
warnings_are_errors: false
env:
 global:
  secure: tQlbpmgwkYV9/ENOxv0hFen814M3GyVpKW1lfM+jkJbwoG4elg73994na6mq84o6VyhXW8ReWk/mYl+CkBHi1LK1g3fnQvD3CcxdX6My1Be5i40HpIuFcgjjUp7iTmsI6ORfjWbSout3A8izpTD6mJYGIZuJZPf31GjQozGEUWWIVxn+jidlbx67Zzyrm2A6tS15Pwo3boQ0iM6kk27CCxgON0kCzoTzopZDf0Yy5yYW2uh9lRj3sz0fgNI7kkAPE/VgS1W36V2NAo4e8FN3jBexatxYT/09tCsPTJ+qAODbSss/5xrQAqZKhnTpQkA/K/B2lwglaG2cyJOyuXCe77uCD5GLFDUj7XPR92akHsTUcqxXDj2tFOmwEv76YhL1ps459ak/I9pVG1uG+KsKxwEXBoD0Sb9DzNjAMUcOP9bJrOYIyWiuagsycGH7UFemyXM6empE0NMF14Yej1CWRqca4K6W/CsPt/EpZE1abcKFWs+TpmyhofFdjIEqgg3fT1baH3lUuUHTeT8qQOGa+JO2geAgH1hIDcPz5jxsUGXWk3GktKi5fuEH/R1HCxCPpSPK9wql1JJYPjLTtnPC+kzFeQrRlBI6NlsOVCdEMBFcpFkYdXYeK03hwAJoHr4jNd7Fup7QFUVQQfZ8q6a6FL7aqn9vJWor7Ynors9BOCA=
before_script: chmod +x update-json-index.sh
after_success: ./update-json-index.sh

